#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = HYPRCURSOR_SIZE,32
env = GTK_THEME,Dracula
env = HYPRCURSOR_THEME,rose-pine-hyprcursor

