#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = HYPRCURSOR_SIZE,32
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = XCURSOR_THEME,rose-pine-cursor
env = XCURSOR_SIZE,32
env = GTK_THEME,Dracula
