#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

#env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = GTK_THEME,Dracula
env = ELECTRON_OZONE_PLATFORM_HINT , auto
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
