#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch:

exec-once = waybar
exec = bash $HOME/.config/hypr/scripts/cycle_wallpapers.sh
exec-once = lact
exec-once = floorp