#################
### AUTOSTART ###
#################

# Autostart necessary processes
exec-once = waybar
exec-once = swww-daemon & bash $HOME/.config/hypr/scripts/cycle_wallpapers.sh
#exec = bash $HOME/.config/hypr/scripts/wallpaperengine.sh

